export default {
  checkers: require('./checkers.png'),
  carDiscover: require('./carDiscover.png'),
  repair: require('./repair.png'),
  personalizedCar: require('./personalizedCar.png'),
  tracking: require('./tracking.png'),
  coinWallet: require('./coinWallet.png'),
  car: require('./car.png'),
  logo: require('./logo.png'),
  success: require('./success.png'),
  biometrics: require('./biometrics.png'),
  notification: require('./notification.png'),
  location: require('./location.png'),
  welcome: require('./welcome.png'),
  empty: require('./empty.png'),
  marker: require('./marker.png'),
  garageMarker: require('./garageMarker.png'),
};
